### ISSUE TITLE
Logging status

### ISSUE THREAD

**Issue by Neex101** [YetiTool/console-raspi3b-plus-platform#7]
Describe what the current status of logging is

**Comment by Klazomenai** [comment]
**Current state of logging**

- **System** logs are found under `/var/log/`, with log rotate defined in `/etc/logrotate.d/`. This is all good.
- **Kivvy** logs are currently under `/home/pi/.kivy/logs`. Log config is defined in `/home/pi/.kivy/config.init` under the `[kivy]` section. Config needs changing to point logs to `/var/log/yeti`. There is also a problem: log rotate does **not** work: `log_maxfiles = x` appears to be ignored! This is a high priority and will raise ticket to address this. The bulk of system logs are not being logged since redirect was removed in the service file
- **GCodes** are only recorded under the `GCode monitor` panel in the UI. These also need to be logged to a file for completeness with appropriate timestamps. Will discuss in Slack on priority for this.

**Ticket suggestions**

- [Investigate why `log_maxfiles = x` is being ignored](https://github.com/YetiTool/console-raspi3b-plus-platform/issues/13)
- [Move Kivy logs to the `/var/log/yeti` directory](https://github.com/YetiTool/console-raspi3b-plus-platform/issues/14)
- [Create a `/var/log` partition](https://github.com/YetiTool/console-raspi3b-plus-platform/issues/15)
- [Investigate systemd-logs-using-Journalctl for EasyCut](https://github.com/YetiTool/console-raspi3b-plus-platform/issues/16)
